# Render deployment configuration file

services:
  # Web service for the Flask app
  - type: web
    name: webhook-data-viewer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    branch: main
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
